# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenSPP DRIMS - Disaster Response Inventory Management",
    "summary": "Disaster relief inventory management for donations, requests, "
    "and distribution tracking. Links to hazard incidents with multi-tier "
    "approval workflows and warehouse operations.",
    "category": "OpenSPP/Inventory",
    "version": "19.0.3.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/OpenSPP2",
    "license": "LGPL-3",
    "development_status": "Beta",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "mail",
        "stock",
        "spp_alerts",
        "spp_base_common",
        "spp_security",
        "spp_vocabulary",
        "spp_area",
        "spp_hazard",
        "spp_gis",
        "spp_gis_report",
        "spp_service_points",
        "spp_approval",
        "spp_cel_domain",
        "spp_audit",
        "job_worker",
    ],
    "data": [
        # Security (must be first)
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/rules.xml",
        # Data
        "data/ir_sequence.xml",
        "data/vocabulary_namespaces.xml",
        "data/vocabulary_codes.xml",
        "data/cel_variables.xml",
        "data/ir_cron.xml",
        "data/audit_rules.xml",
        "data/config_defaults.xml",
        "data/gis_report_templates.xml",
        "data/approval_definitions.xml",
        # Reports (before views, as views may reference report actions)
        "report/waybill_template.xml",
        "views/dashboard_views.xml",
        # Menu structure (parent menus needed by wizards and views)
        "views/menu_structure.xml",
        # Wizards (before views, as views may reference wizard actions)
        "wizard/bulk_approve_wizard.xml",
        "wizard/request_reject_wizard_views.xml",
        "wizard/report_4w_wizard_views.xml",
        "wizard/stock_adjustment_wizard_views.xml",
        "wizard/inter_warehouse_transfer_wizard_views.xml",
        "wizard/allocation_preview_wizard_views.xml",
        "wizard/create_return_wizard_views.xml",
        "wizard/inspection_wizard_views.xml",
        # Views
        "views/alert_views.xml",
        "views/donation_views.xml",
        "views/hazard_incident_views.xml",
        "views/request_views.xml",
        "views/request_template_views.xml",
        "views/return_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_warehouse_views.xml",
        "views/stock_quant_views.xml",
        "views/stock_lot_views.xml",
        "views/product_views.xml",
        "views/personnel_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/activity_feed_views.xml",
        "views/gis_views.xml",
        # Wizards that inherit views (must load after views)
        "wizard/request_from_template_wizard_views.xml",
        # Menus with actions (loaded last, after all views define their actions)
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "spp_drims/static/src/js/hide_dispatch_form_create.js",
            "spp_drims/static/src/js/inspection_list_renderer.js",
            "spp_drims/static/src/js/qty_split_progress_field.js",
            "spp_drims/static/src/xml/qty_split_progress_field.xml",
            "spp_drims/static/src/css/inspection_wizard.css",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
